# Generated by Cascade
from django.db import migrations, models
from django.conf import settings


def seed_products(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    products = [
        {"id": 1, "name": "Red T-Shirt", "price_cents": 1999, "currency": "usd", "active": True},
        {"id": 2, "name": "Blue Jeans", "price_cents": 4999, "currency": "usd", "active": True},
        {"id": 3, "name": "Sneakers", "price_cents": 7999, "currency": "usd", "active": True},
    ]
    for p in products:
        Product.objects.update_or_create(
            id=p["id"],
            defaults={
                "name": p["name"],
                "price_cents": p["price_cents"],
                "currency": p["currency"],
                "active": p["active"],
            },
        )


def unseed_products(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    Product.objects.filter(id__in=[1, 2, 3]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(seed_products, unseed_products),
    ]
